// Generated by https://quicktype.io
export interface IVdfLocation {
    id:                    number;
    //url:                   string;
    //location_code:         string;
    city:                  string;
    //location:              string;
    //alias:                 null;
    //location_type:         string;
    address:               string;
    zip_code:              string;
    //nuts3:                 string;
    country:               string;
    //longitude:             string;
    //latitude:              string;
    //sla:                   null;
    //lessor:                string;
    //owner:                 string;
    //num_of_rooms:          null;
    //num_of_racks:          null;
    //num_of_active_devices: null;
    //num_of_poles:          null;
    //num_of_rr_services:    null;
};
