/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-explicit-any */
//const sql = require("mssql");
import connection from "./connection";

class Location {
   
    public static getByAddress(address?: string): Promise<any[]> {
        return new Promise<any[]>((resolve, reject) => {

            /*
            sql.connect(this.config, function (err: any) {
    
                if (err) console.log(err);
        
                // create Request object
                const request = new sql.Request();
                
                const query = address ? `select * from [v_locations] where [address] like '%${address}%'` : 'select * from [v_locations]';

                // query to the database and get the records
                request.query(query, function (err: any, recordset: any) {
                    
                    if (err) console.log(err)
        
                    // send records as a response
                    resolve(recordset);
                });
            });
            */

            if (address) {
                connection("locations").where("address", 'like', `%${address}%`).then((rows) => {
                    resolve(rows);
                });
            }
            else{
                connection("locations").then((rows) => {
                    resolve(rows);
                });
            }
        });
    }

}

/*
Location.getByAddress().then((list)=>{
    console.log('getByAddress list', list);
});
*/

export default Location;


// Generated by https://quicktype.io


